### ISSUE TITLE
Missing Table in Sql FIle

### ISSUE THREAD

**Issue by amritcoder** [manoharys/VideoTube#2]
Base table or view not found: 1146 Table 'VideoTube.subscribers' doesn't exist in www\metube\includes\classes\User.php on line 84

That's why nothing can do that every page after login shows blank. Like upload.php or any other pages.

**Comment by rahilpathan** [comment]
> That's why nothing can do that every page after login shows blank. Like upload.php or any other pages.

I agree with amrit, wasn't able to replicate getting the same error. @manoharys could you please help?

**Comment by Nama** [comment]
Yes, that's a problem for all new installations.

You can run this in the database to make it work:
```sql
create table subscribers (userTo CHAR, userFrom CHAR);
```
No idea if this is entirely correct, but the contents of the sites are shown now.

Edit: There are more errors like that. Not worth for me checking out...
> PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'VideoTube.DisLikes' doesn't exist in /var/www/html/VideoTube/includes/classes/Video.php:116\nStack trace:\n#0 /var/www/html/VideoTube/includes/classes/Video.php(116): PDOStatement->execute()\n#1 /var/www/html/VideoTube/includes/classes/VideoInfoControls.php(39): Video->getVideoDisLikes()\n#2 /var/www/html/VideoTube/includes/classes/VideoInfoControls.php(15): VideoInfoControls->videoDisLikeButton()\n#3 /var/www/html/VideoTube/includes/classes/VideoInfo.php(24): VideoInfoControls->create()\n#4 /var/www/html/VideoTube/includes/classes/VideoInfo.php(16): VideoInfo->getVideoPrimaryInfo()\n#5 /var/www/html/VideoTube/watch.php(30): VideoInfo->create()\n#6 {main}\n  thrown in /var/www/html/VideoTube/includes/classes/Video.php on line 116

**Comment by koubaki** [comment]
there is also no comments table
the entire project is not usable  except if you modify it
